### ISSUE TITLE
Clarification on LIFT Architecture Used in Results

### ISSUE THREAD

**Issue by kennethyangg** [shijxcs/LIFT#10]
Hi authors,

Thank you for the great work! I noticed that apart from Table 6, the paper does not explicitly mention which architecture is used for LIFT in other results. I would like to confirm:

Does "LIFT (ours)" in the paper all refer to using AdaptFormer?
Or does it represent the best result among various settings (e.g., arbitrary, LoRA, adapter, etc.)?
I ask because I ran the arbitrary setting and achieved an 82.7% accuracy on CIFAR-100, while the paper reports an 81.7% accuracy, which was run with AdaptFormer.

Looking forward to your clarification!

Best regards,
Kenneth

**Comment by shijxcs** [comment]
Hi Kenneth, we default to use AdaptFormer for LIFT because it performs best on ImageNet-LT and Places-LT. We have not ever compared different lightweight modules on CIFAR-100. It is interesting that arbitrary performs better. Maybe it is relevant to the hyperparameters settings.

**Comment by kennethyangg** [comment]
Cool! Thank you for the replying!
