### ISSUE TITLE
Request for Code to Visualize Inter-Class and Intra-Class Feature Distributions

### ISSUE THREAD

**Issue by kennethyangg** [shijxcs/LIFT#5]
Hi, thanks for the great work! I was wondering if you could provide the code for visualizing inter-class feature similarities and intra-class distributions (similar to the figure in the paper)?
![image](https://github.com/user-attachments/assets/e05ecc3c-0a73-428e-8b0e-dd218aa62463)

Best,
Kenneth

**Comment by shijxcs** [comment]
Thank you for your attention! We have uploaded the visualization code in [plot](https://github.com/shijxcs/LIFT/tree/main/plot).

**Comment by kennethyangg** [comment]
Cool! Thank you so much for providing the visualization code, I really appreciate your support! Hope you and the team are doing well!!
